### ISSUE TITLE
Include record type

### ISSUE THREAD

**Issue by rolandtoth** [marcelofinamorvieira/datocms-plugin-project-exporter#1]
Thank you for this plugin, we started using it for various tasks and it saves a lot of time to us.

However, it would be good to also have the record type (`_modelApiKey` or `__typename`) in the export JSON so it would be easy to identify the records we need. Currently we have to rely on a specific field or `item_type.id` values, but the latter might vary between DatoCMS instances.

**Comment by marcelofinamorvieira** [comment]
Added in https://github.com/marcelofinamorvieira/datocms-plugin-project-exporter/commit/7cc55936b6897f0ca1644705a1da3f06bd93d5e2 

Thank you! @rolandtoth
